<?php

/**
 * BaseBanner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $url
 * @property string $image
 * @property string $active
 * @property Doctrine_Collection $Videos
 * @property Doctrine_Collection $VideoBanner
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getTitle()       Returns the current record's "title" value
 * @method string              getUrl()         Returns the current record's "url" value
 * @method string              getImage()       Returns the current record's "image" value
 * @method string              getActive()      Returns the current record's "active" value
 * @method Doctrine_Collection getVideos()      Returns the current record's "Videos" collection
 * @method Doctrine_Collection getVideoBanner() Returns the current record's "VideoBanner" collection
 * @method Banner              setId()          Sets the current record's "id" value
 * @method Banner              setTitle()       Sets the current record's "title" value
 * @method Banner              setUrl()         Sets the current record's "url" value
 * @method Banner              setImage()       Sets the current record's "image" value
 * @method Banner              setActive()      Sets the current record's "active" value
 * @method Banner              setVideos()      Sets the current record's "Videos" collection
 * @method Banner              setVideoBanner() Sets the current record's "VideoBanner" collection
 * 
 * @package    tvonline
 * @subpackage model
 * @author     David Joan Tataje Mendoza <new.skin007@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBanner extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_banner');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             'notnull' => true,
             ));
        $this->hasColumn('url', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             'notnull' => true,
             ));
        $this->hasColumn('image', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             'notnull' => true,
             ));
        $this->hasColumn('active', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'fixed' => 1,
             'notnull' => true,
             'default' => 1,
             ));


        $this->index('i_active', array(
             'fields' => 
             array(
              0 => 'active',
             ),
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
        $this->option('boolean_columns', array(
             0 => 'active',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Video as Videos', array(
             'refClass' => 'VideoBanner',
             'local' => 'banner_id',
             'foreign' => 'video_id'));

        $this->hasMany('VideoBanner', array(
             'local' => 'id',
             'foreign' => 'banner_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             'created' => 
             array(
              'name' => 'created_by',
              'type' => 'integer',
              'onUpdate' => 'CASCADE',
              'onDelete' => 'SET NULL',
              'options' => 
              array(
              'notnull' => true,
              'default' => 1,
              ),
             ),
             'updated' => 
             array(
              'name' => 'updated_by',
              'type' => 'string',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggableext0);
        $this->actAs($signable0);
    }
}