<?php

/**
 * BannerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BannerTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object BannerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Banner');
    }

  const
    STATUS_ACTIVE       = 1,
    STATUS_INACTIVE     = 0;

  protected static
    $status                = array
                             (
                               self::STATUS_ACTIVE     => 'Si',
                               self::STATUS_INACTIVE   => 'No',
                             );

  public function getStatuss()
  {
    return self::$status;
  }


    public function getPathDir() {
        return sfConfig::get('app_banner_images_dir');
    }

    public function getImagePath() {
        return sfConfig::get('app_banner_images_path');
    }
}