<?php

/**
 * CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends DoctrineTable
{
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Category');
  }

  /**
   * Returns an instance of this class.
   *
   * @return object CategoryTable
   */
  
  const
    STATUS_ACTIVE       = 1,
    STATUS_INACTIVE     = 0;
    
  protected static
    $status                = array
                             (
                               self::STATUS_ACTIVE     => 'Si'  ,
                               self::STATUS_INACTIVE   => 'No',
                             );
                             
  public function getStatuss()
  {
    return self::$status;
  }	
  
  public function findOneBySlug($slug)
  {
    $q = $this->createQuery('a')
      ->addWhere('a.id = ?', $slug);
  return $q->fetchOne();
  }
  
  public function getNewRank()
  {
  	 $q = $this->createQuery('a')
  	           ->addSelect('MAX(rank)');
  	           
  	 $dato = $q->execute()->getFirst()->toArray();
  	 return $dato['MAX']+1;
  	 
  }
  
  public function getPadre($slug)
  {
    $q = $this->createQuery('c')
         ->leftJoin('c.Translation t')
         ->addWhere('c.id = ?', $slug);
    return $q->fetchOne();
  }
  
  function updateQueryForList(DoctrineQuery $q)
  {             
    $q->addSelect('c.*,t.name name_str')
      ->leftJoin('c.Translation t')
      ->addWhere('t.lang = ?', 'es')
      ->addWhere('t.name <> ?', sfConfig::get('app_root'));
  }
  
  public function getPathDir()
  {
    return sfConfig::get('app_category_images_dir');
  }
  
  public function getImagePath()
  {
    return sfConfig::get('app_category_images_path');
  }
  
  public function getMenu($lang = 'es')
  {
    $q = $this->createQuery('c')
         ->leftJoin('c.Translation t')
         ->addWhere('t.lang = ?', $lang)
         ->addWhere('c.id <> ?', 1)
         ->addWhere('c.active = ?', 1)
         ->orderBy('c.rank') ;
    return $q->execute();
  }
  
}