<?php

/**
 * Video
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tvonline
 * @subpackage model
 * @author     David Joan Tataje Mendoza <new.skin007@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Video extends BaseVideo
{
  public function generatePathFilename($file)
  {
    $this->setSize(filesize($file->getTempName()));
    $this->setFullMime($file->getType());
    
    return Stringkit::fixFilename($file->getOriginalName()).'_'.rand(11111, 99999).$file->getOriginalExtension();
  }
  
  public function getActiveStr()
  {  	
  	$actives = $this->getTable()->getStatuss();
  	return $actives[$this->getActive()];
  }
  
  public function getNewStr()
  {  	
  	$actives = $this->getTable()->getNews();
  	return $actives[$this->getNew()];
  }  

  public function getTypeStr()
  {  	
  	$actives = $this->getTable()->getTypes();
  	return $actives[$this->getType()];
  }
  
  public function getTitleEs()
  {
  	return sprintf('%s',$this->Translation['es']->title);
  }
  public function getLineIdName()
  {
   	return $this->getLine()->Translation['es']->title;
  }
  
  public function getTitleFull()
  {
  	return sprintf('<br/>es: %s<br/>en: %s',$this->Translation['es']->title,$this->Translation['en']->title);
  }
  
  public function getFormattedDatetime($format = 'D')
  {
    return $this->getTable()->getDateTimeFormatter()->format($this->getCreatedAt(), $format);
  }
    
  public function save(Doctrine_Connection $conn = null)
  {
    parent::save($conn);
  }
  
  public function setVideo($variable)
  {
      
        $variable = str_replace('<br /><a href="http://www.ustream.tv/" style="padding: 2px 0px 4px; width: 400px; background: #ffffff; display: block; color: #000000; font-weight: normal; font-size: 10px; text-decoration: underline; text-align: center;" target="_blank">Broadcasting live with Ustream</a>', '', $variable);
        $variable = str_replace('<br /><a href="http://www.ustream.tv/" style="padding: 2px 0px 4px; width: 400px; background: #ffffff; display: block; color: #000000; font-weight: normal; font-size: 10px; text-decoration: underline; text-align: center;" target="_blank">Streaming by Ustream</a>', '', $variable);
        $variable = str_replace('<br /><a href="http://www.ustream.tv/facebook" style="padding: 2px 0px 4px; width: 400px; background: #ffffff; display: block; color: #000000; font-weight: normal; font-size: 10px; text-decoration: underline; text-align: center;" target="_blank">Live Video app for Facebook by Ustream</a>', '', $variable);
        
        $variable = preg_replace('/([Ww]idth="[0-9]{3}")/', 'width="320"', $variable);
        $variable = preg_replace('/([Hh]eight="[0-9]{3}")/', 'height="309"', $variable);
        $variable = preg_replace('/([Ww]idth: "[0-9]{3}px")/', 'width: 320px', $variable);
        
    $this->_set('video', $variable);
      
  }
  

}
