<?php

/**
 * VideoBannerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VideoBannerTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object VideoBannerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VideoBanner');
    }
}