<?php

/**
 * Video
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tvonline
 * @subpackage model
 * @author     David Joan Tataje Mendoza <new.skin007@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Video extends BaseVideo
{
  public function generatePathFilename($file)
  {
    $this->setSize(filesize($file->getTempName()));
    $this->setFullMime($file->getType());
    
    return Stringkit::fixFilename($file->getOriginalName()).'_'.rand(11111, 99999).$file->getOriginalExtension();
  }
  
  public function getActiveStr()
  {  	
  	$actives = $this->getTable()->getStatuss();
  	return $actives[$this->getActive()];
  }
  
  public function getNewStr()
  {  	
  	$actives = $this->getTable()->getNews();
  	return $actives[$this->getNew()];
  }  
  
  public function getLiveStr()
  {  	
  	$actives = $this->getTable()->getLives();
  	return $actives[$this->getLive()];
  }   

  public function getTypeStr()
  {  	
  	$actives = $this->getTable()->getTypes();
  	return $actives[$this->getType()];
  }
  
  public function getTitleEs()
  {
  	return sprintf('%s',$this->Translation['es']->title);
  }
  public function getLineIdName()
  {
   	return $this->getLine()->Translation['es']->title;
  }
  
  public function getTitleFull()
  {
  	return sprintf('<br/>es: %s<br/>en: %s',$this->Translation['es']->title,$this->Translation['en']->title);
  }
  
  public function getFormattedDatetime($format = 'D')
  {
    return $this->getTable()->getDateTimeFormatter()->format($this->getCreatedAt(), $format);
  }
    
  public function save(Doctrine_Connection $conn = null)
  {
    parent::save($conn);
  }
  

}
