# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  live:
    file: "perutvonline.sdp"
    provider: "rtmp"
    streamer: "rtmp://883286553.r.cdnstreaming.net/live-883286553"
  contact_form:
    ## Put here your email address. This email will receive the message from contact form
    email:         perutvonline@hotmail.com
 
    ## custom your error message            
    error:        There is an error. Cannot be sent!
 
    ## custom your success message
    notice:       Your message has been sent succefull
 
    ## captcha error message
    captcha:      Your secret code is incorrect
 
 
    ## put here the absolute image path
    image_path:  /es/imagen.png
 
    ## legend your form
    legend:       Please, fill the fields and send us a message 
 
    ## change fields labels
    field_name:     Your Name
    field_email:    Your Email
    field_subject:  Your Subject
    field_message:  Your Message
    field_captcha:  Security Code
    button:         Send Message