prod:
  logger:
    class:                   sfNoLogger
    param:
      level:                 err
      loggers:               ~
  mailer:
    class: sfMailer
    param:
      logging:           %SF_LOGGING_ENABLED%
      charset:           %SF_CHARSET%
      delivery_strategy: realtime
      transport:
        class: Swift_SendmailTransport


#  mailer:
#    class: sfMailer
#    param:
#      logging:           %SF_LOGGING_ENABLED%
#      charset:           %SF_CHARSET%
#      delivery_strategy: realtime
#      transport:
#        class: Swift_SmtpTransport
#        param:
#          host:        smtp.plugin.com.br
#          port:       25
#          encryption: ~
#          username:  pcOSCARAR
#          password:   machuoda

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: none

dev:
  mailer:
    param:
      delivery_strategy: none

all:
  routing:
    class:                   sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  storage:
    class:                   sfSessionStorage
    param:
      session_name:          perutvonline
      
  user:
    class:                   UserFrontend
    param:
      timeout:               180000
      logging:               %SF_LOGGING_ENABLED%
      use_flash:             true
      default_culture:       es
  mailer:
    class: sfMailer
    param:
      logging:           %SF_LOGGING_ENABLED%
      charset:           %SF_CHARSET%
      delivery_strategy: realtime
      transport:
        class: Swift_SendmailTransport
    