live:
  url:             /live/:sf_culture/:slug/:category
  param:           { module: Home, action: live, category: '1', sf_culture: 'es' }
  requirements:    { slug: \w+, category: \d+ }
  
playlist:
  url:             /perutvonline/playlist.:sf_format
  param:           { module: Home, action: playlist,  sf_format: xml}

homepage:
  url:             /:sf_culture/:category
  param:           { module: Home, action: show, category: '1', sf_culture: 'es' }
  requirements:    { category: \d+ }
  
load_category:
  url:             /load/category/:category
  param:           { module: Home, action: category, category: '1' }
  requirements:    { category: \d+ }

contact:
  url:   /:sf_culture/contact
  param: { module: contact, action: index, sf_culture: 'es' }

image:
  url:   /:sf_culture/imagen.png
  param: { module: contact, action: image, sf_culture: 'es' }

default:
  url:             /:module/:action/*