default:
  http_metas:
    content-type: text/html
  metas:
    title:         Perú TV online | perutvonline.com
    description:   Television Peruana para el mundo entero
    keywords:      tv,online,peru,television,en,vivo,es,live,stream
    language:      es
    robots:        index, follow
    copyright:     Journal Comunication S.A.C
    geo.region:    PE
    geo.position:  -12.051198,-77.034094
    ICBM:          -12.051198,-77.034094    
   
  stylesheets:
    - frontend/main.css:         { position: first }

  javascripts:
    - jquery/jquery-1.4.2.min.js
    - frontend/jquery.jcarousel.min.js

  has_layout:     true
  layout:         layout