default:
  http_metas:
    content-type: text/html
  metas:
    title:         Perú TV online | Esta donde estas
    description:   "perutvonline, primer sistema peruano de televisión vía Internet con programación propia, continuada online y on-demand las 24 Hrs. del día . Estamos en el Ciberespacio desde enero del 2007. perutvonline es desarrollado por Journal Communications, empresa peruana con más de 15 años de experiencia en el campo de la comunicación audiovisual"
    keywords:      tv,online,peru,television,en,vivo,es,live,stream,flash,turismo,entretenimiento,cultura,noticias,publicidad,empresas
    language:      es
    robots:        index, follow
    copyright:     Journal Comunication S.A.C
    geo.region:    PE
    geo.position:  -12.051198,-77.034094
    ICBM:          -12.051198,-77.034094    
   
  stylesheets:
    - frontend/main.css: { position: first }
    - fancybox/jquery.fancybox-1.3.4.css: { position: first }

  javascripts:
    - jquery/jquery-1.4.2.min.js
    - frontend/jquery.jcarousel.min.js
    - jwplayer/jwplayer.js
    - jquery/jquery-ui-1.8.min.js
    - fancybox/jquery.mousewheel-3.0.4.pack.js
    - fancybox/jquery.fancybox-1.3.4.pack.js
    - frontend/jquery.cycle.js

  has_layout:     true
  layout:         layout