Category:
  tableName:                           t_category
  actAs:
    NestedSet:
      hasManyRoots: true
      rootColumnName: root_id  
    Signable:
      created:
        name: created_by
        type: integer
        onUpdate: CASCADE
        onDelete: SET NULL
        options:
          notnull: true
          default: 1
      updated:
        name: updated_by
        type: string
    Timestampable:
    I18n:
      fields: [name, description]
  columns:
    id:                                { type: integer  , length: 20 , primary: true    , autoincrement: true            }
    rank:                              { type: integer  , length: 20                                                     }
    name:                              { type: string   , length: 100                    , notnull: true                 }
    description:                       { type: string   , length: 5000                   , notnull: true                 }
    image:                             { type: string   , length: 200                   , notnull: false                 }    
    active:                            { type: string   , length: 1  , fixed: true      , notnull: true , default: 0     } 
  indexes:
    i_active:                          { fields: [ active ]                                                              }
  relations:
    Video:                             { class: Video , local: id,   foreign: category_id , type: many , alias: Videos   }
  options:
    symfony:                           { filter: false, form: true }
    boolean_columns:                   [ active ]